//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioInformationCenter.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioInformationCenter.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить.
        /// </summary>
        public static string ID_CAPTION_Apply {
            get {
                return ResourceManager.GetString("ID_CAPTION_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Селекция по времени.
        /// </summary>
        public static string ID_CAPTION_ChoiceByTime {
            get {
                return ResourceManager.GetString("ID_CAPTION_ChoiceByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата/Время.
        /// </summary>
        public static string ID_CAPTION_DateTime {
            get {
                return ResourceManager.GetString("ID_CAPTION_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончание.
        /// </summary>
        public static string ID_CAPTION_EndTime {
            get {
                return ResourceManager.GetString("ID_CAPTION_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string ID_CAPTION_Information {
            get {
                return ResourceManager.GetString("ID_CAPTION_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протоколирование выходной информации РИЦ.
        /// </summary>
        public static string ID_CAPTION_LoggingOutpuRIC {
            get {
                return ResourceManager.GetString("ID_CAPTION_LoggingOutpuRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протоколирование входной информации РИЦ.
        /// </summary>
        public static string ID_CAPTION_RecordingInputRIC {
            get {
                return ResourceManager.GetString("ID_CAPTION_RecordingInputRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало.
        /// </summary>
        public static string ID_CAPTION_StartTime {
            get {
                return ResourceManager.GetString("ID_CAPTION_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип сообщения.
        /// </summary>
        public static string ID_CAPTION_TypeMessage {
            get {
                return ResourceManager.GetString("ID_CAPTION_TypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протоколирование работы РИЦ.
        /// </summary>
        public static string ID_CAPTION_WorkRIC {
            get {
                return ResourceManager.GetString("ID_CAPTION_WorkRIC", resourceCulture);
            }
        }
    }
}
